module.exports = {
  USER_CONNECTED:'USER_CONNECTED',
  // MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
  // MESSAGE_SENT:'MESSAGE_SENT',
  USER_DISCONNECTED:'USER_DISCONNECTED',
  // TYPING:'TYPING',
  VERIFY_USER:'VERIFY_USER',
  OTHER_DISCONNECTED: 'OTHER_DISCONNECTED',
  OTHER_SENT: 'OTHER_SENT',
  SELF_SENT: 'SELF_SENT'
  // LOGOUT:'LOGOU'
}